<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robot" nsURI="http://www.example.org/robot" nsPrefix="robot">
  <eClassifiers xsi:type="ecore:EClass" name="Robot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
        eType="#//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="return" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="RotateCommand" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectionCommand" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" eType="#//Distance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpeedCommand" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Distance" abstract="true" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CM" eSuperTypes="#//Distance"/>
  <eClassifiers xsi:type="ecore:EClass" name="mm" eSuperTypes="#//Distance"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReadSensorCommand" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="DistanceSensorCommand" eSuperTypes="#//ReadSensorCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSensorCommand" eSuperTypes="#//ReadSensorCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//ExpressionBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmetiqueExp" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExp" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//SecondaryExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//SecondaryExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="#//SecondaryExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//SecondaryExp"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpr" eSuperTypes="#//ArithmetiqueExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="#//Call"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondaryExp" eSuperTypes="#//ArithmetiqueExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" upperBound="-1"
        eType="#//ArithmetiqueExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arithmetiqueexp" lowerBound="1"
        eType="#//ArithmetiqueExp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclarationVariable" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressionbase" eType="#//ExpressionBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallVariable" eSuperTypes="#//Call"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallFunction" eSuperTypes="#//Call"/>
  <eClassifiers xsi:type="ecore:EClass" name="Call" abstract="true" eSuperTypes="#//ExpressionBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionBase" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Affectation" eSuperTypes="#//ExpressionBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="callvariable" eType="#//CallVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressionbase" upperBound="-1"
        eType="#//ExpressionBase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpr" eSuperTypes="#//BooleanExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="#//Call"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondaryExp" eSuperTypes="#//BooleanExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//BooleanExp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" upperBound="-1"
        eType="#//BooleanExp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//SecondaryExp.1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//SecondaryExp.1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//SecondaryExp.1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equals" eSuperTypes="#//SecondaryExp.1"/>
</ecore:EPackage>
